Update bug.md with ocm version (#99)
With ocm v2 CLI, `ocm --version` is no longer a valid command. It should
be `ocm version`

>  ocm --version
Error: unknown flag: --version

Signed-off-by: Chris Schneider <11681+ChrisSchneider@users.noreply.github.com>